services:
  app:
    build: .
    container_name: artisan_market_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=artisan_market
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret

  db:
    image: mysql:8.0
    container_name: artisan_market_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: artisan_market
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./artisan_data:/var/lib/mysql
